### ISSUE TITLE
resolver bugs na release 0.1

### ISSUE THREAD

**Issue by PhilipeeX** [desenvolvendo-me/applify#67]
Possivelmente o CI/CD não está com o comportamento esperando, considerando que após PR aprovado alguns testes não estão passando.

Bugs a serem resolvidos:

- [x] Migrações duplicadas
![Image](https://github.com/desenvolvendo-me/applify/assets/85847179/61e391ac-79b9-46ca-a59e-7b69e0bfb543)

- [x] Testes quebrando na release
![Image](https://github.com/desenvolvendo-me/applify/assets/85847179/622859fc-016e-4831-ac66-7b82ba9c9d19)

- [x] Rever e consertar o arquivo de CI/CD ?
Aquivo de CI/ CD não precisou ser alterado, na documentação mostra que a configuração de pull request já é suficiente pra pushs com alterações após o PR.
https://docs.github.com/pt/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore

**Comment by cassiosantana** [comment]
Muito bom trabalho.

**Comment by ricardo-benicio** [comment]
Parabéns @PhilipeeX!!

**Comment by PhilipeeX** [comment]
💓
